const actions = {
    SET_STATE: 'SET_STATE',
    GET_DATA: 'GET_DATA',
    FETCH_DATA: 'FETCH_DATA',
    MARK_AS_FAV: 'MARK_AS_FAV',
    MARK_AS_UNFAV: 'MARK_AS_UNFAV',
    APPEND_FAV_LIST: 'APPEND_FAV_LIST',
    REMOVE_FROM_FAV_LIST: 'REMOVE_FROM_FAV_LIST'
  }
  
  export default actions
  